# Generated by Django 5.1 on 2024-08-31 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_reaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
